### PR TITLE
Update arm11.bin

### PR DESCRIPTION
**Pull request by mariogamer2**

### CODE REVIEW

**Comment by mariogamer2** [comment]
All these request update to this commit:

https://github.com/b1l1s/2xrsa/commit/c3f93cb492d61978fd0620d715510932837495dd

**Comment by Plailect** [comment]
The Section III arm11.bin is a different one than Section IV that only dumps OTP and does not launch arm9.bin. In addition, I will be moving this guide to OTP helper relatively soon, so these won't be needed.

**Comment by mariogamer2** [comment]
Where the one who dump only OTP?

**Comment by Plailect** [comment]
I'm not sure if the source is available, bilis wrote it for me a while back.

**Comment by mariogamer2** [comment]
OTP helper is not suggested at all...

**Pull request closed without merging**
